#!/usr/bin/env bash
# DHCP lease hook for registration/unregistration of DNS
# Copyright (c) 2018-2026 EPAM Systems Inc.

set -Eeuo pipefail

LIBEXEC_DIR="$(dirname "$(realpath "$0")")"
readonly LIBEXEC_DIR

: "${RUNTIME_DIRECTORY:?RUNTIME_DIRECTORY undefined}"
: "${CONFIGURATION_DIRECTORY:?CONFIGURATION_DIRECTORY undefined}"

action="${1:?action required}"
mac="${2:-}"
ip="${3:-}"
host="${4:-}"

exec "${LIBEXEC_DIR}/network-helper" lease-event "$action" "$mac" "$ip" "$host"
