#!/usr/bin/env bash
# DHCP lease hook for registration/unregistration of DNS
# Copyright (c) 2018-2026 EPAM Systems Inc.

set -Eeuo pipefail

LIBEXEC_DIR="$(dirname "$(realpath "$0")")"
readonly LIBEXEC_DIR

: "${RUNTIME_DIRECTORY:?RUNTIME_DIRECTORY undefined}"

main() {
    local action="${1:?action required}"
    local mac="${2:-}"
    local ip="${3:-}"
    local host="${4:-}"

    exec env "RUNTIME_DIRECTORY=${RUNTIME_DIRECTORY}" \
        "${LIBEXEC_DIR}/network-helper" lease-event "$action" "$mac" "$ip" "$host"
}

main "$@"
